version: '3.9'
services:
  nats:
    image: docker.io/nats:2.9.14
    command:
      - "--debug"
      - "--http_port=8222"
      - "--js"

  app:
    build: .
    environment:
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats

